# Generated by Django 5.0.6 on 2024-07-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id_asunto', models.AutoField(db_column='idAsunto', primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('correo', models.EmailField(max_length=40, unique=True)),
                ('motivo', models.TextField(max_length=300)),
                ('asunto', models.ForeignKey(db_column='idAsunto', null=True, on_delete=django.db.models.deletion.CASCADE, to='noticia.asunto')),
            ],
        ),
    ]
