# Generated by Django 5.0.6 on 2024-07-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('tipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='noticia.tiponoticia')),
            ],
        ),
    ]
