# Generated by Django 5.0.6 on 2024-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeusuario',
            name='correo',
            field=models.EmailField(max_length=40),
        ),
    ]
