# Generated by Django 5.0.6 on 2024-07-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_alter_mensajeusuario_correo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
