# Generated by Django 5.0.6 on 2024-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(default='', max_length=200),
        ),
    ]
